package Chess;

public enum ChessBoardFieldStatus {
    PAWN_WHITE, KNIGHT_WHITE, BISHOP_WHITE, ROOK_WHITE, QUEEN_WHITE, KING_WHITE, PAWN_BLACK, KNIGHT_BLACK, BISHOP_BLACK,
    ROOK_BLACK, QUEEN_BLACK, KING_BLACK, EMPTY
}
